# Остановить контейнер
# docker compose -f vault-docker-compose.yml down -v

# Останови Vault
# docker compose -f vault-docker-compose.yml stop vault

# Удалить старый контейнер
# docker rm -f vault

# В dev mode Vault хранит данные в памяти контейнера. Поэтому после перезапуска/пересоздания контейнера секреты исчезают.
# Лучше сделать persistent Vault, чтобы после перезагрузки Ubuntu секреты оставались.

services:
  vault:
    image: hashicorp/vault:1.20
    container_name: vault
    restart: always
    ports:
      - "8200:8200"
    cap_add:
      - IPC_LOCK
    environment:
      VAULT_ADDR: http://127.0.0.1:8200
    volumes:
      - vault-data:/vault/data
      - ./vault/config:/vault/config
    command: vault server -config=/vault/config/vault.hcl

volumes:
  vault-data: